<?php
/**
 * @file
 * site_common module
 */


/**
 * Implements hook_ctools_plugin_directory().
 */
function site_common_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return 'plugins/' . $plugin;
  }
  if ($module == 'panels' && !empty($plugin)) {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_views_api().
 */
function site_common_views_api() {
  return array(
    'api' => 3.0,
  );
}
