<?php
/**
 * @file
 * Module hooks.
 */


define('WMC_IMPORT_VIEW_QUERY_CAMPUS_BY_TITLE', 'wmc_query_campuses_by_title');
define('WMC_IMPORT_LEVEL_UDEGRATUATE', 'UG');
define('WMC_IMPORT_LEVEL_UDEGRATUATE_WITH_FOUNDATION', 'FC');
define('WMC_IMPORT_LEVEL_POSTGRADUATE', 'PG');
define('WMC_IMPORT_LEVEL_FOUNDATION_COURSE', 'FD');


function wmc_import_tests_cron() {
  $migration = Migration::getInstance('ImportWmcTestCoursesUG');
  $result = $migration->processImport();
  $migration = Migration::getInstance('ImportWmcTestCoursesFC');
  $result = $migration->processImport();
  $migration = Migration::getInstance('ImportWmcTestCoursesFD');
  $result = $migration->processImport();
  $migration = Migration::getInstance('ImportWmcTestCoursesPG');
  $result = $migration->processImport();

  $migration = Migration::getInstance('ImportWmcTestCoursesUGData');
  $result = $migration->processImport();
  $migration = Migration::getInstance('ImportWmcTestCoursesFCData');
  $result = $migration->processImport();
  $migration = Migration::getInstance('ImportWmcTestCoursesFDData');
  $result = $migration->processImport();
  $migration = Migration::getInstance('ImportWmcTestCoursesPGData');
  $result = $migration->processImport();

  $migration = Migration::getInstance('ImportWmcTestCL');
  $update = $migration->prepareUpdate();
  $result = $migration->processImport();

}
